docker:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_name]
        target_label: container_name

      - source_labels: [__meta_docker_container_log_stream]
        target_label: container_log_stream