docker:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"

    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_name]
        target_label: container_name

      - source_labels: [__meta_docker_container_log_stream]
        target_label: container_log_stream