---
- name: create certs directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ certs_dir }}"

- name: copy https certificate files
  copy:
    src: "{{ item }}"
    dest: "{{ certs_dir }}"
  with_items:
    - "{{ certs }}"
