---
certs:
  - /etc/ssl/certs/wildcard.idc.roywong.work.cer
  - /etc/ssl/certs/wildcard.idc.roywong.work.ca.cer
  - /etc/ssl/certs/wildcard.idc.roywong.work.key
  - /etc/ssl/certs/wildcard.idc.roywong.work.fullchain.cer